// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerDemo.Infrastructure.Database;

#nullable disable

namespace TaskManagerDemo.Infrastructure.Migrations
{
    [DbContext(typeof(TaskManagerDbContext))]
    partial class TaskManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TaskManagerDemo.Domain.Users.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e37604b5-2b8e-4db9-a00f-afce5ce31ffa"),
                            Email = "user1@example.com",
                            Role = 0,
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("f0a15867-e199-4567-8595-7369cbb99baa"),
                            Email = "user2@example.com",
                            Role = 0,
                            Username = "user2"
                        },
                        new
                        {
                            Id = new Guid("801059ca-2427-4710-b085-ce84cfe0b800"),
                            Email = "admin@example.com",
                            Role = 1,
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
